### ISSUE TITLE
Minimal standalone polyfill of latest spec?

### ISSUE THREAD

**Issue by josephrocca** [WICG/observable#107]
Is there a minimal script that I can import from jsdelivr/unpkg/etc. to start playing around with the features proposed in this spec? Including `element.on` prototype functionality, rather than just the observable primitives.

I'm not involved in any of the spec work/discussion here at all, and I haven't used any of the packages listed in the "**Userland libraries**" section. It looks like they're either just providing the primitives, or are bundled up with a lot of stuff that's unrelated to this spec.

If someone can point me toward a way to easily test the full experience that this proposal proposes, that would be great.

**Comment by domfarolino** [comment]
Since I've closed #42 for inactivity, I would recommend sticking with `chrome://flags/#observable-api` in Chromium to experiment with the Observable API in its latest form.
