### ISSUE TITLE
Spec: `forEach()` does nothing with "visitor callback controller" AbortController

### ISSUE THREAD

**Issue by domfarolino** [WICG/observable#108]
The "visitor callback controller" is never used to trigger the abort of any signal, I think. So something is wrong here and I need to take a closer look.

**Comment by domfarolino** [comment]
OK so it turns out that "visitor callback controller" _is_ actually used, so this is a non-issue. It just looks like it is not used because bikeshed won't highlight all of the references to it inside the algorithm. That's really weird. @tabatkins do you know why this might be? If you go to https://wicg.github.io/observable/#:~:text=and%20signal%20abort-,visitor%20callback%20controller,-with%20E. and click that variable, notice that the instance of that variable in step 2 of that whole algorithm/div does not highlight...

**Comment by tabatkins** [comment]
The immediate cause is that the final instance of the term is broken across the line in the source, so Bikeshed isn't recognizing it as the same term as the other two instances. But that's probably broken behavior; I should be normalizing whitespace. I wonder if that's a regression from my changes a few months ago?

**Comment by domfarolino** [comment]
Oh interesting. Yeah I guess I'd expect that to still work? At least a lot of WHATWG standards are happy to break in the middle of variable names, so I'd expect bs to handle that. If you could see if that's a recent regression that would be great, or if I can help let me know.

**Comment by tabatkins** [comment]
Ah, yes, I was once again fooled by JS's replace function:

```js
function nameFromVar(el) {
    return el.textContent.replace(/(\s|\xa0)+/, " ").trim();
}
```

That needs to be a global regex. :/

**Comment by domfarolino** [comment]
Ah, nice find! OK I'll close this, and I assume bikeshed will get fixed at some point in the meantime? Thanks for the quick investigation!
