### ISSUE TITLE
Should add the checking subscriber's `active` state to the first step of `next(value)`/`error(error)`/`complete()` methods?

### ISSUE THREAD

**Issue by tetsuharuohzeki** [WICG/observable#114]
These supporting concepts does not check _subscriber_'s [_active_](https://wicg.github.io/observable/#subscriber-active) state.

- https://wicg.github.io/observable/#dom-subscriber-next
- https://wicg.github.io/observable/#dom-subscriber-error
- https://wicg.github.io/observable/#dom-subscriber-complete

And they use as null checking for each of _next/error/complete algorithm_ instead of checking _active_ concept, because of [close a subscription](https://wicg.github.io/observable/#close-a-subscription) concept set _active_ to `false` and set _next/error/complete algorithm_ to null.

However, I feel it's an implicit steps. I also think it's better to use _active_ concept and checking it at the first step of each of subscriber's _next(value)_ / _error(error)_ / _complete()_ concepts.

**Comment by domfarolino** [comment]
Checking algorithm step null-ness vs checking `active` is not equivalent, unfortunately. You can have a `Subscriber` whose algorithms are null (for example, if nobody provided a [`complete()` handler](https://wicg.github.io/observable/#dom-subscriptionobserver-complete)) but is still active. So if `Subscriber#complete()` _only_ checked `active`, it will try and execute the complete steps, which may be null.

Does that make sense?

**Comment by tetsuharuohzeki** [comment]
@domfarolino 

> So if Subscriber#complete() only checked active, it will try and execute the complete steps, which may be null.

By _[subscribe to an Observable](https://wicg.github.io/observable/#observable-subscribe-to-an-observable) concept_, the steps 2 lets a new _internal observer_ and it will be used to initialize _subscriber_ in the step 5.

> https://wicg.github.io/observable/#observable-subscribe-to-an-observable
> 
> 2. Let internal observer be a new [internal observer](https://wicg.github.io/observable/#internal-observer).
> ---
> 5. Let subscriber be a [new](https://webidl.spec.whatwg.org/#new) [Subscriber]> (https://wicg.github.io/observable/#subscriber), initialized as:
> 
>     - [next algorithm](https://wicg.github.io/observable/#subscriber-next-algorithm)
>         - internal observer’s [next steps](https://wicg.github.io/observable/#internal-observer-next-steps)
>      - [error algorithm](https://wicg.github.io/observable/#subscriber-error-algorithm)
>         - internal observer’s [error steps](https://wicg.github.io/observable/#internal-observer-error-steps)
>      - [complete algorithm](https://wicg.github.io/observable/#subscriber-complete-algorithm)
>         - internal observer’s [complete steps](https://wicg.github.io/observable/#internal-observer-complete-steps)
> ....

But  _[internal observer](https://wicg.github.io/observable/#internal-observer)_ has initial value but I read they does not means null: 

> https://wicg.github.io/observable/#internal-observer
> 
> An internal observer is a [struct](https://infra.spec.whatwg.org/#struct) with the following [items](https://infra.spec.whatwg.org/#struct-item):
> **_next steps_**
> An algorithm that takes a single parameter of type [any](https://webidl.spec.whatwg.org/#idl-any). Initially, these steps do nothing.
> **_error steps_**
An algorithm that takes a single parameter of type [any](https://webidl.spec.whatwg.org/#idl-any). Initially, the [default > error algorithm](https://wicg.github.io/observable/#default-error-algorithm).
> **_complete steps_**
An algorithm with no parameters. Initially, these steps do nothing.

From these definitions of the current spec and other parts, I seem _next/error/complete algorithm_ would not be null without steps in [_close a subscription_ concept](https://wicg.github.io/observable/#close-a-subscription).

**Comment by domfarolino** [comment]
> From these definitions of the current spec and other parts, I seem next/error/complete algorithm would not be null without steps in [close a subscription concept](https://wicg.github.io/observable/#close-a-subscription).

Looks like you're right, good catch! Feel free to send a PR my way to clean this up in the spec, if you'd like.
