### ISSUE TITLE
Observable.from should throw primitive iterables (strings)

### ISSUE THREAD

**Issue by benlesh** [WICG/observable#125]
Along with how [Iterator helpers behave](https://github.com/tc39/proposal-iterator-helpers/issues/275#issuecomment-1502093384), if a user passes a `string`, even though it's an iterable, it's likely an error. We should throw a `TypeError` in that case.

```ts
Observable.from('some string'); // TypeError
```

**Comment by bakkot** [comment]
I think you misread my comment (which was not all that clear, sorry). `Iterator.from` does _not_ throw when given a string. This makes it different from `flatMap`, which _does_ throw when the mapper returns a string, even though strings are iterable.

See discussion in https://github.com/tc39/proposal-iterator-helpers/issues/244..

**Comment by petamoriken** [comment]
FYI: `ReadableStream.from` rejects `string` https://github.com/whatwg/webidl/pull/1397

**Comment by ljharb** [comment]
If someone is intentionally passing a string into an `X.from` method, they explicitly want to convert a string into an X. I think this is the one case where an iterable string must be accepted.

**Comment by flensrocker** [comment]
Can a usecase be returning a string from the catch operator?
How should I do this if Observable.from throws on a string? Or can I just return the string?
(having rxjs of("...") in mind)

**Comment by domfarolino** [comment]
I'm sold on ensuring `Observable.from("string")` works the same as `Observable.from(Object("string"))` does today, by basically adding special handling like https://github.com/tc39/proposal-iterator-helpers/pull/250/files did for Iterator helpers. I'll ensure that this makes it into https://github.com/WICG/observable/pull/160, and I'll close this issue.

**Comment by petamoriken** [comment]
@domfarolino

> I'm sold on ensuring `Observable.from("string")` works the same as `Observable.from(Object("string"))` does today, by basically adding special handling like https://github.com/tc39/proposal-iterator-helpers/pull/250/files did for Iterator helpers.

I think the behavior of `Observable.from(“string”)` and `Observable.from(Object(“string”))` should be clearly separated.

> Any time an iterable or async-iterable value (a value that has a `Symbol.iterator` or `Symbol.asyncIterator` method) is expected, primitives should be treated as if they were not iterable. Usually, this will mean throwing a `TypeError`. **If the user provides a primitive wrapper Object such as a String Object, however, it should be treated like any other Object**.

> NB: This convention is new as of 2024, and most earlier parts of the language do not follow it. In particular, positional destructuring (both binding and assignment), array spread, argument spread, for-of loops, `yield *`, the `Set` and `AggregateError` constructors, `Object.groupBy`, `Map.groupBy`, `Promise.all`, `Promise.allSettled`, `Promise.any`, `Promise.race`, `Array.from`, the static from methods on typed array constructors, and **`Iterator.from` (Stage 3 at time of writing) all accept primitives where iterables are expected**.

https://github.com/tc39/how-we-work/blob/main/normative-conventions.md#reject-primitives-in-iterable-taking-positions

**Comment by petamoriken** [comment]
If you do so, please specify in the specification that primitive `strings` are accepted in exceptional cases.

**Comment by bakkot** [comment]
@petamoriken The normative-conventions wording shouldn't apply to _explicit_ coercion methods like `Iterator.from` and `Observable.from`. (`@michaelficarra`, who wrote that wording, was aware of this at one point, but [he keeps forgetting](https://github.com/tc39/how-we-work/pull/152#issuecomment-2207217873).)

**Comment by petamoriken** [comment]
Well, I don't understand why `ReadableStream.from` doesn't accept primitive `strings` while `Observable.from` does. Does that mean `Observable.from` should be treated as *primitive* as `Iterator.from`?

**Comment by bakkot** [comment]
If I understand correctly [the current plan](https://github.com/whatwg/webidl/pull/1397#issuecomment-2500846493) is for `ReadableStream.from` to accept primitive strings. cc @lucacasonato

**Comment by petamoriken** [comment]
It does not seem so.
FYI: https://github.com/denoland/deno/pull/26882, https://github.com/denoland/deno/pull/25116

**Comment by lucacasonato** [comment]
@bakkot  No, the plan is to accept boxed strings, but not primitive strings

**Comment by bakkot** [comment]
Ah. Well, that's unfortunate. In that case I have no opinion about what `Observable.from` should do, since it can't be consistent with both.

**Comment by ljharb** [comment]
The entire point of a "from" method is to explicitly convert from one type to another. It's the one place rejecting strings makes no sense, and if Readable.from wants to be the weird one, that doesn't mean Observable.from should join it.

**Comment by lucacasonato** [comment]
Actually what I said may be wrong. I have to read thru the discussion again. Specifically the `async iterable` webidl type will not directly accept string primitives. However we might have decided something else for `ReadableStream.from`. I will have to check again.

**Comment by benlesh** [comment]
@bakkot and @ljharb thank you for the insight. This makes total sense to me. I'm just used to seeing operators like `flatMap` implement in terms of `Observable.from(fn(value, index++))` or whatever, and in those cases, in RxJS at least, it's almost always a bug when someone returns a string from a `switchMap`, `flatMap`/`concatMap`, `mergeMap` etc.
