### ISSUE TITLE
Why do teardowns call `error(error)` when thrown?

### ISSUE THREAD

**Issue by keithamus** [WICG/observable#156]
In the [close a subscription steps](https://wicg.github.io/observable/#close-a-subscription), step 4.2 says:

> 4.2. [Invoke](https://webidl.spec.whatwg.org/#invoke-a-callback-function) teardown.
>    - If [an exception E was thrown](https://webidl.spec.whatwg.org/#an-exception-was-thrown), call subscriber’s [error()](https://wicg.github.io/observable/#dom-subscriber-error) method with E.

However, step 2 sets the `active` boolean to `false`, and step 1 of the [error(error) method steps](https://wicg.github.io/observable/#dom-subscriber-error) are:

> 1. If [this](https://webidl.spec.whatwg.org/#this)'s [active](https://wicg.github.io/observable/#subscriber-active) is false, [report the exception](https://html.spec.whatwg.org/multipage/webappapis.html#report-the-exception) error, then return.

So AIUI, this means any invocation of a teardown function that results in an exception can _only_ get reported, and calling `error(error)` is pointless. Is this correct?

It looks like Chrome doesn't actually do these steps, either; Chrome calls [`teardown->InvokeAndReportException(nullptr)`](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/dom/subscriber.cc;l=186?q=subscriber.cc) instead of setting up a `v8::TryCatch` and passing any caught exceptions to `error(error)`.

So should the spec by altered? Or am I missing something?

**Comment by domfarolino** [comment]
I agree this seems wrong. The [`addTeardown()` method][1] seems to agree with me too, in that if it is called when the subscription is already closed, the teardown immediately invokes and globally reports any exceptions. @benlesh do you agree, that under no circumstance a teardown should forward things to a downstream error handler?

[1]: https://wicg.github.io/observable/#dom-subscriber-addteardown
