### ISSUE TITLE
error callback / complete callback are not actually used in inspect

### ISSUE THREAD

**Issue by Jamesernator** [WICG/observable#174]
The [inspect method](https://wicg.github.io/observable/#dom-observable-inspect) defines `error callback` and `complete callback`, however it never actually calls them inside `error`/`complete` observer methods.

The steps should probably be similar to the steps for the next callback (i.e. passing thrown errors to `subscriber.subscribe`).

**Comment by Jamesernator** [comment]
One consideration, perhaps for error we should be using [`SuppressedError`](https://github.com/tc39/proposal-explicit-resource-management?tab=readme-ov-file#the-suppressederror-error) from the (currently being implemented) explicit resource management proposal for the error case.

i.e. The steps would be equivalent to:

```js
error: (error) => {
    try {
        errorCallback?.(error);
        subscriber.error(error);
    } catch (inspectError: unknown) {
        subscriber.error(
            new SuppressedError(
                inspectError,
                error,
                `inspector error callback threw an error`,
            ),
        );
    }
},
```

**Comment by domfarolino** [comment]
Thanks for catching this. I'll fix the immediate bug to bring it inline with the implementation (https://github.com/WICG/observable/pull/176), and link to https://github.com/WICG/observable/issues/150 to consider the explicit resource management proposal as a follow-up.

**Comment by domenic** [comment]
I think it might be worth a separate issue to discuss the `SupressedError` idea in particular, as it's a change in semantics, apart from the addition of `Symbol.dispose`.

**Comment by domfarolino** [comment]
Done (https://github.com/WICG/observable/issues/177) thanks!
