### ISSUE TITLE
Is it worth showing possible APIs that could be built with observable?

### ISSUE THREAD

**Issue by benlesh** [WICG/observable#25]
There are some APIs that we don't have that Observable might be really good for... for example, dealing with "upload then download" sort of XHR and fetch semantics is frankly ugly most of the time. Where a single stream of something shaped like `{ status, progress, data }` or the like makes for a pretty interesting/ergonomic way to build UIs on top of such things. WebSockets are another one... they start connecting, then open, or close (clean or unclean), or error, they get messages, etc. All of that could be sent through one stream of events, and it makes it so the developer doesn't have to know the dance between different events.

**Comment by domfarolino** [comment]
My 2c is yes, the more examples the better! We can turn some of these into non-normative code examples in the specification one it exists too, but getting them in the explainer for now would be wonderful.

**Comment by domfarolino** [comment]
Given the inactivity here, it seems like the answer is no sadly! I'll close this out since it's not being worked on.
