### ISSUE TITLE
Feedback from me with a Node perspective

### ISSUE THREAD

**Issue by benjamingr** [WICG/observable#30]
Hey, Ben sent me this proposal, _we're_ likely happy to adopt it in Node though I'll raise it internally with the project for feedback. I'm in the TSC now so I need to be more careful with accidentally sounding like I speak for the whole project which I don't.

In terms of API I think it's important to consider compatibility with https://github.com/tc39/proposal-iterator-helpers and https://github.com/tc39/proposal-explicit-resource-management . 

Regarding the "history" section, I don't think TC39 was ever opposed to the proposal they just had concerns though WHATWG may be a better standards body for it given the deep web platform integration (e.g AbortSignal support would be hard through TC39).

Regarding "prior art" - I think stuff like MobX/Vue.reactive etc are the same thing but it's a hard case to make @headinthebox makes it ([here](https://www.youtube.com/watch?v=SVYGmGYXLpY)).

Regarding concerns with promises - I'm wondering if being able to preventDefault/stopPropagation is actually important for these promise returning events. I've seen this concern raised many times when discussing streams in Node and in practice we shipped the iterator-helpers proposal and streams are otherwise mostly synchronous and no one noticed or complained in practice so from my PoV it's not a problem in practice (and neither is firehose to be fair).

**Comment by benjamingr** [comment]
(Personally I am excited and happy you picked this up and are working on this, I was an advocate of the older effort)

**Comment by benlesh** [comment]
> In terms of API I think it's important to consider compatibility with https://github.com/tc39/proposal-iterator-helpers and https://github.com/tc39/proposal-explicit-resource-management .

Full agreement.

To that end, I had told @domfarolino that we should try to align the API with the iterator helpers. I don't think we've explicitly discussed disposable/resource management... however, I'm amenable to a lot of things here, and I think it's a good add. In RxJS land, we're going to add `Symbol.dispose` to `Subscription`, which will basically just alias `unsubscribe`.

**Comment by ljharb** [comment]
fwiw i think this utterly belongs in TC39 and nowhere else, and if there's now browser interest, that feels like it would help it feel motivated - so i hope you bring it back to TC39.

**Comment by benlesh** [comment]
> fwiw i think this utterly belongs in TC39 and nowhere else

Years ago when I wrote the WHATWG issue, discussing with @domenic, he believed it did _not_ belong in the TC39. And that was the general feedback that put things on hold way back in 2015, IIRC. I don't know if @jhusain still monitors his github (I hope he doesn't, because he's living the dream right now), but maybe he recalls.

**Comment by ljharb** [comment]
That was not my sense being in the room at those times, but either way the makeup of the committee and the state of the language is quite different than it was 8 years ago, so I strongly urge you to reattempt it.

**Comment by domfarolino** [comment]
Thanks a lot for the feedback @benjamingr! I think given https://github.com/wintercg/proposal-common-minimum-api/issues/72 and https://github.com/nodejs/standards-positions/issues/1, we can probably close this issue now. Also, the remaining points of feedback here I believe are captured by other issues that have been filed against this proposal in the intervening time.

Specifically, see https://github.com/WICG/observable/issues/150 for talks of resource management and disposability. And see https://github.com/WICG/observable/issues/148 for discussion of `unsubscribe()` if we decided that the ["synchronous firehose"](https://github.com/WICG/observable/issues/12) problem is not significant enough to justify the clunkiness of forcing users into AbortControllers & AbortSignals for unsubscription.
