### ISSUE TITLE
Standards tracking

### ISSUE THREAD

**Issue by keithamus** [WICG/observable#93]
This issue provides references to the various standards issues:

- Mozilla Standards position (no signals yet): https://github.com/mozilla/standards-positions/issues/945
- WebKit Standards position (no signals yet): https://github.com/WebKit/standards-positions/issues/292
- Chrome Platform Status: https://chromestatus.com/feature/5154593776599040
- WinterCG: https://github.com/wintercg/proposal-common-minimum-api/issues/72
- TAG Review (not yet reviewed): https://github.com/w3ctag/design-reviews/issues/902
- Node: https://github.com/nodejs/standards-positions/issues/1

**Comment by anlexN** [comment]
`Observable` has a very long history, today, it is time to have a result.

**Comment by domfarolino** [comment]
Note that I closed this in favor of https://github.com/WICG/observable?tab=readme-ov-file#standards-issues, since I don't think this information has to necessarily be bound to an open issue on the repository.
